import AppKit

/// Polls the system pasteboard and records every new copy into the store.
/// macOS has no "clipboard changed" notification, so polling `changeCount` is the standard approach.
final class ClipboardMonitor {
    private let pasteboard = NSPasteboard.general
    private let store: ClipStore
    private var lastChangeCount: Int
    private var timer: Timer?

    var isPaused = false
    /// Called after something new was recorded.
    var onCapture: (() -> Void)?

    // Types that password managers and similar apps set to ask clipboard tools not to record them.
    private let ignoredTypes: Set<NSPasteboard.PasteboardType> = [
        .init("org.nspasteboard.ConcealedType"),
        .init("org.nspasteboard.TransientType"),
        .init("org.nspasteboard.AutoGeneratedType"),
        .init("com.agilebits.onepassword"),
    ]

    init(store: ClipStore) {
        self.store = store
        lastChangeCount = pasteboard.changeCount
    }

    func start() {
        timer = Timer.scheduledTimer(withTimeInterval: 0.4, repeats: true) { [weak self] _ in
            self?.check()
        }
        RunLoop.main.add(timer!, forMode: .common)
    }

    /// Call after the app itself writes to the pasteboard so it doesn't record its own write.
    func skipCurrentChange() {
        lastChangeCount = pasteboard.changeCount
    }

    private func check() {
        let count = pasteboard.changeCount
        guard count != lastChangeCount else { return }
        lastChangeCount = count
        guard !isPaused else { return }

        let types = Set(pasteboard.types ?? [])
        guard types.isDisjoint(with: ignoredTypes) else { return }

        let front = NSWorkspace.shared.frontmostApplication
        let source = ClipStore.Source(name: front?.localizedName, bundleID: front?.bundleIdentifier)

        if let urls = pasteboard.readObjects(forClasses: [NSURL.self],
                                             options: [.urlReadingFileURLsOnly: true]) as? [URL],
           !urls.isEmpty {
            store.addFiles(urls, source: source)
        } else if let png = pngData(types: types) {
            store.addImage(pngData: png, source: source)
        } else if let text = pasteboard.string(forType: .string) ?? plainText(types: types) {
            store.addText(text, rich: richText(types: types), source: source)
        } else {
            return
        }
        onCapture?()
    }

    /// The formatted version of copied text, so it can be pasted with formatting later.
    private func richText(types: Set<NSPasteboard.PasteboardType>) -> ClipStore.RichText? {
        for type in [NSPasteboard.PasteboardType.rtf, .html] where types.contains(type) {
            if let data = pasteboard.data(forType: type), data.count <= 2_000_000 {
                return ClipStore.RichText(data: data, type: type)
            }
        }
        return nil
    }

    /// Text for copies that only carry formatted text (RTF/HTML) and no plain version.
    private func plainText(types: Set<NSPasteboard.PasteboardType>) -> String? {
        for (type, docType) in [(NSPasteboard.PasteboardType.rtf, NSAttributedString.DocumentType.rtf),
                                (.html, .html)] where types.contains(type) {
            if let data = pasteboard.data(forType: type),
               let attributed = try? NSAttributedString(data: data, options: [.documentType: docType],
                                                        documentAttributes: nil) {
                return attributed.string
            }
        }
        return nil
    }

    private func pngData(types: Set<NSPasteboard.PasteboardType>) -> Data? {
        // Text copies can also offer an image rendition; prefer the text then.
        // Only accept real image data, not images macOS would convert from other types.
        if types.contains(.string) || types.contains(.rtf) || types.contains(.html) { return nil }
        guard types.contains(.png) || types.contains(.tiff) else { return nil }
        if let png = pasteboard.data(forType: .png) { return png }
        if let tiff = pasteboard.data(forType: .tiff),
           let rep = NSBitmapImageRep(data: tiff) {
            return rep.representation(using: .png, properties: [:])
        }
        return nil
    }
}
